server:
  port: 8700

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: prod
    #active: test
#    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

# sm.ms 图床的 token
smms:
  token: 1oOP3ykFDI0K6ifmtvU7c8Y1eTWZSlyl

jmshop:
  # 快鸟物流查询配置
  express:
    enable: true
#    appId: 1706217
#    appKey: a120300a-f6f3-4b8a-842e-058f4e44a779
    appId: 1790093
    appKey: e4b0ece5-fc91-4066-ad49-fa0a95adaeae
  # 配置
  apiUrl: https://wxmp.zhuozhong.net.cn/api

#华为云OBS云存储
huaweicloud:
  obs:
    end_point: obs.cn-south-1.myhuaweicloud.com
    accessible_domain_name: https://zhuozhong-mall.obs.cn-south-1.myhuaweicloud.com
    access_key_id: KA1V7LLDFN6O8KJQNXDZ
    secret_access_key: w25sh84S4oUUYeJTz343ly9peb2D0vwfQaOhiIBE
    bucket_name: zhuozhong-mall
    local_file_path: /www/wwwlogs
    cloud_file_path: mall/objservice
